# Generated by Django 5.0.1 on 2024-02-05 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_remove_stock_created_at_remove_stock_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='time_period_slider',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
