# Generated by Django 5.0.1 on 2024-02-05 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_stock_time_period_slider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
