# Generated by Django 5.0.1 on 2024-02-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_alter_stock_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='selected_time_period',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
