# Generated by Django 5.0.3 on 2024-04-08 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_stock_selected_time_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='selected_time_period',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='time_period_slider',
        ),
    ]
